

#cloud-config
users:
   - name: core
ssh_authorized_keys:
   - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiHEAQ7nUkuI3wX/wDqogyPe4/ZP2gaMW7zu1KQdjhjwN5gtVD5rS8gyoU1yi7LCcsKyFL1q4BVtAKAnY0fDa9Frull4YcMGVbdpNidLCnwoQh+jrUxeYjLNub6Tqo2aQWZeqg60v9NYZV7b9I145xOPB1XDUJptYoLBtTVERnnWTdkcy1GsDUeQSJmpxKn/Q3kb+IxyAGa2wno+/vtZQy4DMZuHdbhbgMigm81ht85KMOZouUKbr+kI2ZJU4bJpmi7d+1bjOOqaESi+cWG1wurO813NNFWj720TX0/s8K/ODAL96gFMvgwxD6AUOrGPkVQNUqHHhEQO/zfNsIKBWf core@localhost

coreos:
  etcd2:
    discovery: https://discovery.etcd.io/7f196af1ef3fa1209acc20fb9e29c9bf
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379, http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380 
  units:
    - name: etcd2.service
      command: start
    -name: fleet.service
      command: start    
    - name: vmtoolsd.service
      command: start
      content: |
        [Unit]
        Description=VMware Tools Agent
        Documentation=http://open-vm-tools.sourceforge.net/
        ConditionVirtualization=vmware

        [Service]
        ExecStartPre=/usr/bin/ln -sfT /usr/share/oem/vmware-tools /etc/vmware-tools
        ExecStart=/usr/share/oem/bin/vmtoolsd
        TimeoutStopSec=5
  oem:
    bug-report-url: "https://github.com/coreos/bugs/issues"
    id: vmware
    name: VMWare
    version-id: "9.10.0"
