#cloud-config
users:
   - name: core
ssh_authorized_keys:
   - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDB2IRtZmg+wLoKSPoDwLg1CMt4E9Vkhdeynz7Swnp4hLtif9B6RBG0tqF8RSjg6L/YRRBIw4ijCa2t8XkWpX2FE/L+tcJhClepWC5pyfeuHS/uHJGxT7C133A1PXduW1L1wcyegq0nAGeGMb/rlTB3NqGxgBaGwctVcySaWOiAW+VG6NEuUXBe5qOpuaUveKnZgajh3/06vVJmQ/0PRggbBWZx5hUkbTOr9yLstvXGZLYh2dPIQM5DaGdFgrEkS3TJiga+BlcQ8QWkPH2Y8kZq35FBvnb/OYQjj8D83lDCTJHQYkyKJP8SuGOlnCavLWcP3VsB4CGPTuHGRT0Fm8a9 core@localhost

coreos:
  etcd2:
  discovery: https://discovery.etcd.io/7f196af1ef3fa1209acc20fb9e29c9bf
  advertise-client-urls: http://10.27.96.135:2379, http://10.27.96.135:4001
  initial-advertise-peer-urls: http://10.27.96.135:2380
  listen-client-urls: http://0.0.0.0:2379, http://0.0.0.0:4001
  listen-peer-urls: http://10.27.96.135:2380
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: vmtoolsd.service
      command: start
      content: |
        [Unit]
        Description=VMware Tools Agent
        Documentation=http://open-vm-tools.sourceforge.net/
        ConditionVirtualization=vmware

        [Service]
        ExecStartPre=/usr/bin/ln -sfT /usr/share/oem/vmware-tools /etc/vmware-tools

        ExecStart=/usr/share/oem/bin/vmtoolsd
        TimeoutStopSec=5
  oem:
    bug-report-url: "https://github.com/coreos/bugs/issues"
    id: vmware
    name: VMWare
    version-id: "9.10.0"
